name: ch05
version: 0.0.1+1
description: A minimal command-line application.
#author: First Last <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
